version: '3.8'
services:
  web:
    build: .            # Construye desde el Dockerfile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./src:/app/src  # Opcional: montar código para desarrollo